#!/bin/bash
# plase checkout this code before you running it !!!

read -p "wheher update and upgrade your package (recommand)[y/n]" response
read -p "input proxy ip" your_proxy_ip
read -p "input proxy port" your_proxy_port

# code snipper checkout if docker is exists
if docker --version;then
	continue
else 
	sudo apt install docker.io
fi
# whether update package
if [[ $response ~ '^(y|Y)' ]];then
    sudo apt update && sudo apt upgrade
fi

sudo mkdir -p /etc/systemd/system/docker.service.d
sudo touch /etc/systemd/system/docker.service.d/http_proxy.conf
echo -e "[Service]\n Environment=\"HTTP_PROXY=http://$your_proxy_ip:$your_proxy_port/\"" > $_

sudo touch /etc/systemd/system/docker.service.d/https_proxy.conf
echo -e "[Service]\n Environment=\"HTTPS_PROXY=http://$your_proxy_ip:$your_proxy_port/\"" > $_

sudo systemctl daemon-reload
sudo systemctl restart docker

