#!/bin/env bash

install_nvm() {
    if [[ -s "$HOME/.nvm" || -d "$HOME/.nvm" ]];then
        echo -e "you had have nvm"
    else
       read -r -p "Do you decide to install nvm in this computer" dec
       if [[ $dec != "no" && $dec != "N" && $dec != "n" ]];then
           code="curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash"
          if [[ $code == 0 ]];then
              echo -e "Success \n"
          else
              echo -e "Fail \n"
          fi
      fi
    fi
}

initial_nvim_config() {
  # create .config/nvim format
  if [[ -d $HOME/.config/nvim || -L $HOME/.config/nvim ]]; then
    echo -e "nvim config file existed, do you want to override it? \n"
    read -p "yes/no" ans
    if [[ $ans ~= "^n|N" ]]; then
      exit 0
    fi

    # make .config direcotry
    (
      rm -rf "$HOME/.config/nvim" \
        && { make -p "$HOME/.config/nvim" && ln -s $HOME/.dotfile/nvim $HOME/.config }
    )
  else
    make -p "$HOME/.config/nvim" && ln -s $HOME/.dotfile/nvim $HOME/.config
  fi
  echo -e "please access nvim/lua/plugins/plugins-setup.lua the type :PackerSync"

}


initial_vim() {
    # delete .vim fold
    [[ -d "$HOME/.vim" || -f "$HOME/.vim" || -L "$HOME/.vim" ]] && rm -r "$HOME/.vim"

    # make a direct vim    
    mkdir -p "$HOME/.vim"

    # make vim fold struct
    if [[ -d "$HOME/.vim" ]];then
        mkdir -p "$HOME"/.vim/autoload
        mkdir -p "$HOME"/.vim/backup
        mkdir -p "$HOME"/.vim/colors
        mkdir -p "$HOME"/.vim/plugged

        curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim \
        || {echo -e "not connect github \n"; exit 2}
    fi
}


# Initial VIM
echo "Whether to create stand-form directory link for vim: "
read -r -p "yes/no: " ans
if [[ $an =~ ^[Y|y] ]];then
    initial_vim
elif [[ $ans =~ ^[N|n] ]];then
    echo -e "No Link be created\n"
fi

# Initial NVIM
echo "Whether to create stand-form directory link for Neovim: "
read -r -p "yes/no: " ans
if [[ $an =~ ^[Y|y] ]];then
   install_nvm && initial_nvim_config || {echo "Initial NVIM Fail" && exit 3}
elif [[ $ans =~ ^[N|n] ]];then
    echo -e "No Link be created\n"
fi
