#!/bin/env bash

# install tmux command
sudo apt install tmux -y || exit 2

# install tldr command
sudo apt install tldr || exit 3
tldr test > /dev/null 2>&1 ||  echo "tldr --update fail"; exit 4 

# install shellcheck
sudo apt install shellcheck || echo "shellcheck faile"; exit 5

# install exa comamnd
version_ubuntu=$(lsb_release -a 2>/dev/null | grep -Ei 'description' | awk '{print $3}' | awk -F '.' '{print $1}')
if [[ $version_ubuntu -ge 24 ]]; then
  sudo apt install exa || exit 1
else
  ( mkdir -p "$HOME"/Download \
    cd "$HOME"/Download/ \
    && wget https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip \
    && apt install unzip  \
    && unzip exa-linux-x86_64-0.9.0.zip \
    && mv exa-linux-x86_64 /usr/local/bin/exa \
    && rm -f "$HOME"/Download ) || exit 2
fi
