set-option -g prefix C-a
bind-key C-a send-prefix

# Enable mouse mode
set -g mouse on

# Enable two prefixes
set-option -g prefix C-a
set-option -g prefix2 C-b

# use system clipborard
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard"
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel "xclip -selection clipboard"

