# set color in tmux
set -g default-terminal "screen-256color"

# Enable mouse mode
set -g mouse on

# Enable two prefixes
set -g prefix C-a
unbind C-b
set-option -g prefix C-a
#set-option -g prefix2 C-b

set-option -sg escape-time 10
set-option -g focus-events on

# Add customize Status bar
set -g status on
set -g status-right "#[fg=white]%H:%M"
