#!/bin/bash

source ~/.dotfile/initial/colors.sh
path='/etc/systemd/system'

res=$([[ -f $path/frpc.service || -L $path/frpc.service ]] && rm -f $path/frpc.service 2>&1)


if [[ $res =~ permission ]];then
    echo -e -n "use below code after ${RED}you modify frpc.service file \n${RESET}"
    echo -e -n "sudo bash setup_frp"
fi

ln -s ~/.dotfile/importFile/frpc/frpc.service $path \
    || echo -e "not initial frpc.server for systemctl command, may be your systemctl have frpc.server" 1>&2 \
    && echo -e "initial frps to systemctl command is successful"


